name: ✅ Tests

on: [push]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build-type: [Release]
    steps:
      -
        uses: actions/checkout@v2
      -
        name: 🔧 expected
        run: |
          cmake -E make_directory build
          cmake -DCMAKE_BUILD_TYPE="${{ matrix.build-type }}"   \
                -DCMAKE_INSTALL_PREFIX=build/output             \
                -B build -S .
        shell: bash
      -
        name: 🔨 expected_tests
        run: cmake --build build --config "${{ matrix.build-type }}" --target "tl-expected-tests" -j
      -
        name: ✅ Unit Tests
        run: cd build && ctest --build-config "${{ matrix.build-type }}" --progress --verbose
      -
        name: 📦️ install
        run: cmake --build build --config "${{ matrix.build-type }}" --target install
